### PR TITLE
Emit `InitialSyncDone` notification to allow client to perform auto-a…

### PR DESCRIPTION
**Pull request by NicolasBuquet**
Emit InitialSyncDone notification to allow client to perform auto-activation of cross-signing as in Android client

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [X] Pull request contains a changelog file in ./changelog.d. See https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog
* [X] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by NicolasBuquet** [comment]
@pixlwave Hello Doug.

Can you have a look at this PR. We need it on Tchap.

**Comment by pixlwave** [comment]
Hi Nicolas, I'm a bit confused about the approach of this change. Tchap is a for of EI, so how come you can't use SessionVerificationListener which does the right thing?

**Comment by NicolasBuquet** [comment]
Thank you for your attention @pixlwave.

I was not aware of SessionVerificationListener.

I will have a look at it and check if :  
- I can hook in it at the right moment and in the right state
- I can auto-activate cross-signing without user interaction (the famous grace period) from here

Thank you.

**Comment by NicolasBuquet** [comment]
@pixlwave 

Update to the previous comment. 

AuthenticationCoordinator is used by OnboardingCoordinator in Element.

But OnboardingCoordinator is not used in the custom Onboarding process in Tchap.

So, the simple method is to mimic what is done on the Android side, listen to an `initialSyncDone` notification.

**Comment by NicolasBuquet** [comment]
@pixlwave 

Update to the previous comment. 

AuthenticationCoordinator is used by OnboardingCoordinator in Element.

But OnboardingCoordinator is not used in the custom Onboarding process in Tchap.

So, the simple method is to mimic what is done on the Android side, listen to an `initialSyncDone` notification.

**Pull request closed without merging**
