### PR TITLE
Bug Fix: App crashes on resume

### PR DESCRIPTION
**Pull request by giomfo**
Take into account pending Pause (if any) at the end of resume.

### CODE REVIEW

**Comment by manuroe** [comment]
The pending pause is due to MatrixKit, not the SDK. So the comments about it seem out of scope.
It seems we fix something in the kit but at the sdk level. This is the issue of the 2 async responses for one request (one by callback, one by an event via NSNotificationCenter).

Instead of talking of pending pause, we could indicate in the spec of the methods how the 2 responses are sent (the session state is updated before the call of the callback)
Then the kit will simply conform to them and will no more crash.

**Comment by giomfo** [comment]
First the comment is still relevant, it mentions the SDK user (not the SDK).

You're right about the 2 async responses for one request. This is the weak point. I think we should remove one of them.
The callback is only used to update the user presence (online). This operation may be performed on session state change when the session switches in running mode. I suggest removing the resume callback.

If you agree, I will prepare this change, and update the commit.

**Comment by manuroe** [comment]
> First the comment is still relevant, it mentions the SDK user (not the SDK).
Hmm. The comment looks like the sdk must forecast and anticipate the SDK user behaviour which is strange.

The failure seems to be still required. It would look weird to have a failure callback without a success callback, no?

**Comment by manuroe** [comment]
LGTM

**Comment by giomfo** [comment]
Manu, solution has been change, please review again

**Comment by manuroe** [comment]
LGTM

**Pull request merged**
