### PR TITLE
Cache realm for thread, instead of recreating it on every access

### PR DESCRIPTION
**Pull request by Adlai-Holler**
In unscientific profiling (scrolling through a group chat of mine for about 5 seconds,) `+realmForUser:andDevice:` was crazy expensive. On my iMac Pro, it accounted for 534ms of CPU time. After this patch, it dropped to 21ms.

Screen Shot 2021-01-31 at 2 12 34 PM

Screen Shot 2021-01-31 at 2 15 01 PM

Let me know!

Signed-off-by: Adlai Holler <adlai@icloud.com>

### CODE REVIEW

**Comment by manuroe** [comment]
Thanks @Adlai-Holler for this optimisation:

Can you do the following things, please?

* [ ] Pull request updates [CHANGES.rst](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CHANGES.rst)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

**Comment by Adlai-Holler** [comment]
Sure, done on this one. Changed the approach slightly to make sure we don't leak realms with different userid/deviceid. WDYT?

**Comment by manuroe** [comment]
This improvement is very interesting. I can see those times on my iPhoneX with my matrix account:
```
2021-02-16 18:29:12.347726+0100 Riot[40849:4528662] [MXRealmCryptoStore] realmForUser took 0.474ms
2021-02-16 18:29:12.349777+0100 Riot[40849:4528662] [MXRealmCryptoStore] realmForUser took 0.564ms
2021-02-16 18:29:12.515522+0100 Riot[40849:4528656] [MXRealmCryptoStore] realmForUser took 14.172ms
2021-02-16 18:29:12.905919+0100 Riot[40849:4528680] [MXRealmCryptoStore] realmForUser took 13.663ms
2021-02-16 18:29:13.682404+0100 Riot[40849:4528662] [MXRealmCryptoStore] realmForUser took 13.858ms
2021-02-16 18:29:13.943062+0100 Riot[40849:4528680] [MXRealmCryptoStore] realmForUser took 3.081ms
2021-02-16 18:29:16.683603+0100 Riot[40849:4528662] [MXRealmCryptoStore] realmForUser took 4.345ms
2021-02-16 18:29:16.850570+0100 Riot[40849:4529208] [MXRealmCryptoStore] realmForUser took 3.497ms
2021-02-16 18:29:20.033412+0100 Riot[40849:4528662] [MXRealmCryptoStore] realmForUser took 12.924ms
2021-02-16 18:29:21.773849+0100 Riot[40849:4528662] [MXRealmCryptoStore] realmForUser took 13.849ms
```

I would be very happy to kill them.

Unfortunately, your PR makes the code unstable. I cannot explain it why yet. Is it an issue because we retain too much thread or too much realm instances? I do not know.

The stability issue is visible when running all tests from [MXCryptoTests](https://github.com/matrix-org/matrix-ios-sdk/blob/v0.18.1/MatrixSDKTests/MXCryptoTests.m). I can see around 12 tests failing. They can pass if ran individually but it is not great.
`testAliceAndBobWithNewDevice` is a good example of test that randomly passes when you launch it alone. It passes 1 out of 3 tries.

**Comment by Adlai-Holler** [comment]
Ah, good thing we’ve got those unit tests. I’ll investigate later today.

**Comment by stefanceriu** [comment]
We had another look at this recently and even tried different implementations on the same note but the app remains unstable. Investing more time into it is probably not a good idea and the only feasible solution appears to be to get rid of realm entirely / rewrite the crypto part.

Thank you for taking the time to raise this PR but I think it's time we close it 🙏

**Pull request closed without merging**
