### PR TITLE
Remove the libbase58 pod dependency

### PR DESCRIPTION
**Pull request by ARiezn**
### Summary
Completely remove `libbase58` dependency and replace it with ObjC implementation to manage base58 for keys backup.

### Details
See issue https://github.com/matrix-org/matrix-ios-sdk/issues/1828 for details

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [X] Pull request contains a changelog file in ./changelog.d. See https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog
* [x] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by ARiezn** [comment]
Signed-off-by: Artem Rieznikov <artem.rieznikov@teladochealth.com>

**Comment by pixlwave** [comment]
Hey @ARiezn, thanks for this PR. Unfortunately we won't be able to accept it at this time. Until https://github.com/CocoaPods/CocoaPods/issues/11839 is fixed, we're developing this pod against Xcode 14.2.

Side note: as we're starting to transition to a Rust-backed world with https://github.com/matrix-org/matrix-rust-components-swift/ large changes to this library are unlikely to be accepted.

**Comment by ARiezn** [comment]
@pixlwave , thank you for your attention to my PR. I want to highlight that the change proposed in this PR does not actually require to switch from using Xcode 14.2 for building. It will not break compatibility with Xcode 14.2. So continuation of using the same version of XCode should not be a problem at all. It will only make it possible to build using Xcode 14.3 or above (since the libbase58 dependency is removed). Is it possible to reconsider the decision to close the PR? Let me know if there are some other requirements or necessary changes that I may take into account.

**Comment by pixlwave** [comment]
Hi, sorry I'm afraid not at this time @ARiezn.

**Pull request closed without merging**
